name: Play.Trading CICD

on:
  push:
    branches: ["master"]

jobs:
  generate-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Github Tag Bump
        id: tag_bump
        uses: anothrNick/github-tag-action@1.62.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_v: true
          INITIAL_VERSION: 1.0.2
          DEFAULT_BUMP: patch

    outputs:
      new_version: ${{steps.tag_bump.outputs.new_tag}}

  build-and-publish-container:
    runs-on: ubuntu-latest
    needs: generate-version
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: |
              playeconomy1384.azurecr.io/play.trading:${{needs.generate-version.outputs.new_version}}
          build-args: |
            GITHUB_PAT=${{secrets.GITHUB_TOKEN}}

# Let's see how this works